# Site settings
title: Draft Workshop
#email: rahulpandita@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#  My outlook
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://rahulpandita.me/" # the base hostname & protocol for your site
twitter_username: pandita_rahul
github_username:  rahulpandita

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jemoji


#pagination
paginate: 4
