# Site settings
title: RFC Draft Workshop
#email: rahulpandita@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#  My outlook 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pandita_rahul
github_username:  rahulpandita

# Build settings
markdown: kramdown
